<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>netcoreapp3.1</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Dotmim.Sync.Sqlite" Version="0.6.0" />
    <PackageReference Include="Dotmim.Sync.SqlServer" Version="0.6.0" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Json" Version="5.0.0" />
    <PackageReference Include="Microsoft.Data.Sqlite.Core" Version="5.0.2" />
    <PackageReference Include="Microsoft.IdentityModel.JsonWebTokens" Version="7.7.1" />
    <PackageReference Include="Microsoft.IdentityModel.Protocols" Version="7.7.1" />
    <PackageReference Include="Microsoft.IdentityModel.Protocols.OpenIdConnect" Version="7.7.1" />
    <PackageReference Include="SQLitePCLRaw.bundle_e_sqlcipher" Version="2.0.4" />
    <PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="7.7.1" />
  </ItemGroup>

  <ItemGroup>
    <None Update="appsettings.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="appsettings.local.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>
