#
# Run Checks
#
name: Check

on:
  workflow_dispatch:
  pull_request:

jobs:
  #
  # Run SonarQube scan
  #
  check-sonar-dotnet:
    uses: EdisonInternational/actions/.github/workflows/check-sonar-dotnet.yml@main
    #with:
    #    VERSION: 1.0.0          (optional, default=github.ref_name)
    secrets: inherit
    permissions:
      contents: read
      actions: read
      checks: write
